// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDInqI6RxBIpbPdHoeEQ9B522oDZOYTHk0',
    appId: '1:585682855065:web:8357f4510979d1becc0408',
    messagingSenderId: '585682855065',
    projectId: 'learning-b-41409',
    authDomain: 'learning-b-41409.firebaseapp.com',
    storageBucket: 'learning-b-41409.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzGgFhhfA3lP90-hVABtDEzjEFFZUznjA',
    appId: '1:585682855065:android:77322dd53fc9d383cc0408',
    messagingSenderId: '585682855065',
    projectId: 'learning-b-41409',
    storageBucket: 'learning-b-41409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9u8Yd24b1DxxtrbYOWujYgLoYsoJ_90E',
    appId: '1:585682855065:ios:a3e31abca6f40556cc0408',
    messagingSenderId: '585682855065',
    projectId: 'learning-b-41409',
    storageBucket: 'learning-b-41409.appspot.com',
    iosBundleId: 'com.example.learningb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9u8Yd24b1DxxtrbYOWujYgLoYsoJ_90E',
    appId: '1:585682855065:ios:a3e31abca6f40556cc0408',
    messagingSenderId: '585682855065',
    projectId: 'learning-b-41409',
    storageBucket: 'learning-b-41409.appspot.com',
    iosBundleId: 'com.example.learningb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDInqI6RxBIpbPdHoeEQ9B522oDZOYTHk0',
    appId: '1:585682855065:web:46d5a4aa79485f90cc0408',
    messagingSenderId: '585682855065',
    projectId: 'learning-b-41409',
    authDomain: 'learning-b-41409.firebaseapp.com',
    storageBucket: 'learning-b-41409.appspot.com',
  );

}